<a href="https://colab.research.google.com/github/meghanmagner/Linear-Algebra/blob/main/Gram_Schmidt_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

#Let's figure out how to do vector oporations:

In [3]:
#create a vector:
r1=np.array([1,2,3])
r1

array([1, 2, 3])

In [4]:
#vector arithmetic:
-3*r1

array([-3, -6, -9])

In [5]:
#vector dog products:
r1.dot(r1)

14

In [8]:
#magnitude:
r1.dot(r1)
#need the square root!
#sqrt(14)
(14)**(0.5)
#or
np.sqrt(14)

3.7416573867739413

In [9]:
#magnitutde of vector r1:
np.sqrt(r1.dot(r1))

3.7416573867739413

# Implement Gram Schmidt on 4 Vectors


In [12]:
#Original, Random Vectors:
r1=np.array([3,0,3,0])
r2=np.array([3,2,3,3])
r3=np.array([-7,-4,-5,-6])
r4=np.array([-7,-3,-11,2])
r1, r2, r3, r4

(array([3, 0, 3, 0]),
 array([3, 2, 3, 3]),
 array([-7, -4, -5, -6]),
 array([ -7,  -3, -11,   2]))

# Process $r_1$

In [18]:
#Choose the r1 vecotr and subtract off the "Nice" orthogonal pieces:
t1=r1
print("t1 = ", t1)

#find the size of t1:
m=np.sqrt(t1.dot(t1))
print("The size of t1 is", m)

#The nice vector is u1 = t1/m:
u1=(1/m)*t1
print("The nice vector is u1 =", u1)

t1 =  [3 0 3 0]
The size of t1 is 4.242640687119285
The nice vector is u1 = [0.70710678 0.         0.70710678 0.        ]


In [19]:
#Sanity Check:
print("The size of u1 =", np.sqrt(u1.dot(u1)))

The size of u1 = 1.0


# Process $r_2$

In [21]:
#Choose the r2 vecotr and subtract off the "Nice" orthogonal pieces:
t2=r2 - r2.dot(u1)*u1
print("t2 = ", t2)

#find the size of t2:
m=np.sqrt(t2.dot(t2))
print("The size of t2 is", m)

#The nice vector is u2 = t2/m:
u2=(1/m)*t2
print("The nice vector is u2 =", u2)

t2 =  [3.00000000e+00 2.22044605e-16 3.00000000e+00 4.44089210e-16]
The size of t2 is 4.242640687119286
The nice vector is u2 = [7.07106781e-01 5.23364153e-17 7.07106781e-01 1.04672831e-16]


In [22]:
#Sanity Check:
print("The size of u1 =", np.sqrt(u1.dot(u1)))
print("The size of u2 =", np.sqrt(u2.dot(u2)))

print("u1 . u2=", u1.dot(u2))

The size of u1 = 1.0
The size of u2 = 1.0
u1 . u2= -5.80620396615762e-17


# Process $r_3$

In [26]:
#Choose the r3 vecotr and subtract off the "Nice" orthogonal pieces:
t3=r3 - r3.dot(u1)*u1 - r3.dot(u2)*u2
print("t3 = ", t3)

#find the size of t3:
m=np.sqrt(t3.dot(t3))
print("The size of t3 is", m)

#The nice vector is u3 = t3/m:
u3=(1/m)*t3
print("The nice vector is u3 =", u3)

t3 =  [-1.  0.  1.  0.]
The size of t3 is 1.4142135623730951
The nice vector is u3 = [-0.70710678  0.          0.70710678  0.        ]


In [25]:
#Sanity Check:
print("The size of u1 =", np.sqrt(u1.dot(u1)))
print("The size of u2 =", np.sqrt(u2.dot(u2)))
print("The size of u3 =", np.sqrt(u3.dot(u3)))

print("u1 . u2=", u1.dot(u2))
print("u1 . u3=", u1.dot(u3))
print("u2 . u3=", u2.dot(u3))

The size of u1 = 1.0
The size of u2 = 1.0
The size of u3 = 0.9999999999999999
u1 . u2= -5.80620396615762e-17
u1 . u3= 0.0
u2 . u3= 0.0


# Process $r_4$

In [27]:
#Choose the r4 vecotr and subtract off the "Nice" orthogonal pieces:
t4=r4 - r4.dot(u1)*u1 - r4.dot(u2)*u2 - r4.dot(u3)*u3
print("t4 = ", t4)

#find the size of t4:
m=np.sqrt(t4.dot(t4))
print("The size of t4 is", m)

#The nice vector is u4 = t4/m:
u4=(1/m)*t4
print("The nice vector is u4 =", u4)

t4 =  [ 4.4408921e-16 -3.0000000e+00 -4.4408921e-16  2.0000000e+00]
The size of t4 is 3.6055512754639896
The nice vector is u4 = [ 1.23168186e-16 -8.32050294e-01 -1.23168186e-16  5.54700196e-01]


In [28]:
#Sanity Check:
print("The size of u1 =", np.sqrt(u1.dot(u1)))
print("The size of u2 =", np.sqrt(u2.dot(u2)))
print("The size of u3 =", np.sqrt(u3.dot(u3)))
print("The size of u4 =", np.sqrt(u4.dot(u4)))

print("u1 . u2=", u1.dot(u2))
print("u1 . u3=", u1.dot(u3))
print("u2 . u3=", u2.dot(u3))
print("u1 . u4=", u1.dot(u4))
print("u2 . u4=", u2.dot(u4))
print("u3 . u4=", u3.dot(u4))

The size of u1 = 1.0
The size of u2 = 1.0
The size of u3 = 0.9999999999999999
The size of u4 = 1.0
u1 . u2= -5.80620396615762e-17
u1 . u3= 0.0
u2 . u3= 0.0
u1 . u4= -2.220446049250313e-16
u2 . u4= 1.451550991539401e-17
u3 . u4= -1.7418611898472846e-16
